### ISSUE TITLE
Create SSG proposal:(Mkdocs, Pelican)

### ISSUE THREAD

**Issue by BDadmehr0** [BDadmehr0/Learn-C#1]
# Create SSG proposal: (Mkdocs, Pelican)

## Description

We need to create a comprehensive proposal for using Static Site Generators (SSGs) within our project. This proposal should cover two popular SSGs: Mkdocs and Pelican. The goal is to evaluate these tools and decide which one suits our needs best.

## Tasks

1. **Research and Overview:**
    - Provide a brief introduction to Static Site Generators.
    - Explain why SSGs are beneficial for our project.

2. **Mkdocs:**
    - Overview of Mkdocs.
    - Key features and advantages.
    - Installation and setup process.
    - Example of creating a simple site.
    - Pros and cons.

3. **Pelican:**
    - Overview of Pelican.
    - Key features and advantages.
    - Installation and setup process.
    - Example of creating a simple site.
    - Pros and cons.

4. **Comparison:**
    - Compare Mkdocs and Pelican based on:
        - Ease of use
        - Documentation
        - Community support
        - Customization options
        - Performance

5. **Recommendation:**
    - Provide a recommendation on which SSG to use, based on the comparison and our project requirements.
    - Include any additional considerations or potential issues.

## Additional Information

- Include relevant links to the official documentation of Mkdocs and Pelican.
- If possible, include screenshots or code snippets to illustrate key points.

**Comment by arshavirm** [comment]
hello
i am going to convert the current and re-structure current repo content in mkdocs (since mkdocs is more performant for documentaion creation)

**Comment by BDadmehr0** [comment]
> hello i am going to convert the current and re-structure current repo content in mkdocs (since mkdocs is more performant for documentaion creation)

Hello, thank you for your contribution, I checked your pull request and approved it

How do I run it? Does it have a website address or a special method to run it?

**Comment by arshavirm** [comment]
If you have python3 with pip install just type `pip install mkdocs` in terminal and go to the site directory and open a terminal in that directory and type `mkdocs serve` to run a webserver of the site

**Comment by BDadmehr0** [comment]
This is great, but there are some problems that need to be solved

- [ ] Texts should be written from the right side (for languages such as Arabic and Farsi)
- [ ] The links of "answers to the exercises" are not given.
- [ ] Parts of the texts contain C code that does not have an interesting theme
- [ ] This part of the site should be changed to what is in the source site:
- [**my_site**](https://github.com/BDadmehr0/Learn-C/blob/main/-2147483648_-210101.jpg)
- The chapters should be written as follows:
- [**source_site**](https://github.com/BDadmehr0/Learn-C/blob/main/Screenshot%20from%202024-07-23%2012-23-46.png)
